---
default: true
MD004:
  style: dash
MD007:
  indent: 2
  start_indented: false
MD013:
  code_block_line_length: 80
  heading_line_length: 99
  line_length: 1600
  code_blocks: false
  headings: true
  stern: false
  strict: false
  tables: false
MD025:
  level: 1
  front_matter_title: ""
MD033:
  allowed_elements: [a, br, p, img]
MD041:
  level: 1
  front_matter_title: ""
MD044:
  code_blocks: false
MD046:
  style: fenced
MD048:
  style: backtick
